### ISSUE TITLE
tagname containing dots not supported

### ISSUE THREAD

**Issue by lucab** [dolthub/dolt#1144]
When using `dolt tag`, I got a panic-trace when trying to use `33.20201201.3.0` as tagname. After reading https://github.com/dolthub/dolt/pull/191, I think this is due to limitation in Noms.
For a better user experience, it would be nice to get a human-readable error explaining why the tagname isn't valid, and even better if possible just accept dotted-tags (possibly by encoding them).

```
$ dolt version
dolt version 0.22.7

$ dolt tag 33.20201201.3.0
panic: 
        Error Trace:    try.go:96
                                                try.go:54
                                                database_common.go:131
                                                doltdb.go:888
                                                tag.go:64
                                                tag.go:137
                                                command.go:165
                                                dolt.go:223
                                                dolt.go:106
                                                proc.go:203
                                                asm_amd64.s:1373
        Error:          Invalid dataset ID: refs/tags/33.20201201.3.0


goroutine 1 [running]:
github.com/dolthub/dolt/go/store/d.Panic(0x1970b53, 0x16, 0xc0007e7640, 0x1, 0x1)
        /src/store/d/try.go:54 +0xfb
github.com/dolthub/dolt/go/store/datas.(*database).GetDataset(0xc000504040, 0x1d53780, 0xc000502180, 0xc0006f4f20, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /src/store/datas/database_common.go:131 +0x4df
github.com/dolthub/dolt/go/libraries/doltcore/doltdb.(*DoltDB).NewTagAtCommit(0xc000496030, 0x1d53780, 0xc000502180, 0x1d4a000, 0xc000496c20, 0xc0001e01c0, 0xc00069ae80, 0x0, 0x0)
        /src/libraries/doltcore/doltdb/doltdb.go:888 +0xbc
github.com/dolthub/dolt/go/libraries/doltcore/env/actions.CreateTag(0x1d53780, 0xc000502180, 0xc000506000, 0x7ffe8bd3febf, 0xf, 0x1953f8e, 0x4, 0xc000694640, 0xa, 0xc000655300, ...)
        /src/libraries/doltcore/env/actions/tag.go:64 +0x28e
github.com/dolthub/dolt/go/cmd/dolt/commands.TagCmd.Exec(0x1d53780, 0xc000502180, 0xc0006fc0c8, 0x8, 0xc00011c170, 0x1, 0x1, 0xc000506000, 0x8)
        /src/cmd/dolt/commands/tag.go:137 +0xc95
github.com/dolthub/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x1953e9e, 0x4, 0x196897e, 0x11, 0xc0001a0b40, 0x24, 0x24, 0x0, 0x1d53780, 0xc000502180, ...)
        /src/cmd/dolt/cli/command.go:165 +0x475
main.runMain(0x0)
        /src/cmd/dolt/dolt.go:223 +0xc52
main.main()
        /src/cmd/dolt/dolt.go:106 +0x22
```

**Comment by timsehn** [comment]
Fixed in above.

**Comment by lucab** [comment]
@andrew-wm-arthur @timsehn Thanks for the UX improvement!

For the underlying issue, I'd still like to have dotted tags (tldr: in order to match table ref to some internal software release).
Is there the idea to accept dots in tags (by massaging `dolt` internals) or should I stick with my own external character-substitution trick in the long term?

**Comment by andrew-wm-arthur** [comment]
We definitely plan to support dots in tags. Currently that character is reserved for another use internally. We can make the change, but it's more involved than changing the tag name validation to allow dots.

**Comment by zachmu** [comment]
This no longer panics but you still can't use a dot in tag names, which prevents people from using semver.

**Comment by timsehn** [comment]
I believe this is fixed by: https://github.com/dolthub/dolt/pull/4146.

@zachmu to confirm.

**Comment by timsehn** [comment]
Confirmed this works through test:
```
charsets_collations $ dolt tag 0.1
charsets_collations $ dolt tag
    0.1
```
