### ISSUE TITLE
Out of Range for bigint unsigned with question mark

### ISSUE THREAD

**Issue by yx1215** [dolthub/dolt#6728]
The following script will generate the error `Error 1105 (HY000): -9223372036854775808 out of range for bigint unsigned`:
```go
package main

import (
	"database/sql"
	"fmt"
	sqle "github.com/dolthub/go-mysql-server"
	"github.com/dolthub/go-mysql-server/memory"
	"github.com/dolthub/go-mysql-server/server"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
	engine := sqle.NewDefault(memory.NewDBProvider())

	config := server.Config{
		Protocol: "tcp",
		Address:  fmt.Sprintf("localhost:3307"),
	}

	s, err := server.NewDefaultServer(config, engine)
	if err != nil {
		fmt.Println(err)
		return
	}

	go func() {
		if err := s.Start(); err != nil {
			return
		}
	}()

	conn, err := sql.Open("mysql", "no_user:@tcp(localhost:3307)/")
	_, _ = conn.Exec("CREATE DATABASE demo")
	_, _ = conn.Exec("CREATE TABLE demo.user_info (\n    id BIGINT PRIMARY KEY AUTO_INCREMENT,\n    aid BIGINT UNSIGNED\n)")
	_ = conn.Close()

	db, err := sql.Open("mysql", "no_user:@tcp(localhost:3307)/demo")

	// Error 1105 (HY000): -9223372036854775808 out of range for bigint unsigned
	_, err = db.Exec("INSERT INTO `user_info` (id, aid) VALUES (?, ?)", 0, uint64(9223372036854775808))
	if err != nil {
		fmt.Println(err)
	}

	// success
	_, err = db.Exec("INSERT INTO `user_info` (id, aid) VALUES (0, 9223372036854775808)")
	if err != nil {
		fmt.Println(err)
	}
}
```

Notice that 9223372036854775808 is (max int64) + 1.
The error won't appear for numbers smaller or equal to max int64. 
Also I tried the error only occurs with question mark. If we use raw sql, we won't meet the error.

So I think there might be something wrong with parsing question mark which causes the overflow?(something like parsing uint64 as int64)

**Comment by max-hoffman** [comment]
Moved to dolt repo for easier visibility.

**Comment by JCOR11599** [comment]
Hey @yx1215, thanks for the bug report.
I was able to reproduce the issue, and we have a fix in review.

Heads up, the script you have references an older version of go-mysql-server (v0.17.0).
As a result, the current script will not work correctly when this fix is merged.
Here is an adapted script (following `gms/_example/main.go`), which should work similarly

```golang
package main

import (
	"context"
	"fmt"

	dbsql "database/sql"
	sqle "github.com/dolthub/go-mysql-server"
	_ "github.com/go-sql-driver/mysql"

	"github.com/dolthub/go-mysql-server/memory"
	"github.com/dolthub/go-mysql-server/server"
	"github.com/dolthub/go-mysql-server/sql"
	"github.com/dolthub/go-mysql-server/sql/mysql_db"
	"github.com/dolthub/vitess/go/mysql"
)

var (
	dbName    = "mydb"
	tableName = "mytable"
	address   = "localhost"
	port      = 3307
)

func sessionBuilder(pro *memory.DbProvider) server.SessionBuilder {
	return func(ctx context.Context, conn *mysql.Conn, addr string) (sql.Session, error) {
		host := ""
		user := ""
		mysqlConnectionUser, ok := conn.UserData.(mysql_db.MysqlConnectionUser)
		if ok {
			host = mysqlConnectionUser.Host
			user = mysqlConnectionUser.User
		}

		client := sql.Client{Address: host, User: user, Capabilities: conn.Capabilities}
		baseSession := sql.NewBaseSessionWithClientServer(addr, client, conn.ConnectionID)
		return memory.NewSession(baseSession, pro), nil
	}
}

func main() {
	db := memory.NewDatabase(dbName)
	db.BaseDatabase.EnablePrimaryKeyIndexes()

	pro := memory.NewDBProvider(db)
	engine := sqle.NewDefault(pro)
	sess := memory.NewSession(sql.NewBaseSession(), pro)
	ctx := sql.NewContext(context.Background(), sql.WithSession(sess))
	ctx.SetCurrentDatabase(dbName)

	config := server.Config{
		Protocol: "tcp",
		Address:  fmt.Sprintf("%s:%d", address, port),
	}
	s, err := server.NewServer(config, engine, sessionBuilder(pro), nil)
	if err != nil {
		fmt.Println(err)
		return
	}

	go func() {
		if err := s.Start(); err != nil {
			return
		}
	}()

	conn, err := dbsql.Open("mysql", "no_user:@tcp(localhost:3307)/")
	_, _ = conn.Exec("CREATE DATABASE demo")
	_, _ = conn.Exec("CREATE TABLE demo.user_info (id BIGINT PRIMARY KEY AUTO_INCREMENT, aid BIGINT UNSIGNED)")
	_ = conn.Close()

	mydb, err := dbsql.Open("mysql", "no_user:@tcp(localhost:3307)/demo")

	// Error 1105 (HY000): -9223372036854775808 out of range for bigint unsigned
	_, err = mydb.Exec("INSERT INTO `user_info` (id, aid) VALUES (?, ?)", 0, uint64(9223372036854775808))
	if err != nil {
		fmt.Println(err)
	}

	// success
	_, err = mydb.Exec("INSERT INTO `user_info` (id, aid) VALUES (0, 9223372036854775808)")
	if err != nil {
		fmt.Println(err)
	}
}
```

We will update you once the changes are in.

**Comment by yx1215** [comment]
Regarding the version problem, I saw that the latest version tag on https://github.com/dolthub/go-mysql-server is 0.17.0, are you going to release a version soon?

**Comment by yx1215** [comment]
I've changed https://github.com/dolthub/vitess to the [commit](https://github.com/dolthub/vitess/pull/278) that you tried to fix the issue, the error for insert has been fixed, but we still have a similar issue for select. The following is a script for reproduce the error.

```
package main

import (
	"context"
	"fmt"

	dbsql "database/sql"
	sqle "github.com/dolthub/go-mysql-server"
	_ "github.com/go-sql-driver/mysql"

	"github.com/dolthub/go-mysql-server/memory"
	"github.com/dolthub/go-mysql-server/server"
	"github.com/dolthub/go-mysql-server/sql"
	"github.com/dolthub/vitess/go/mysql"
)

var (
	address = "localhost"
	port    = 3307
)

func sessionBuilder(pro *memory.DbProvider) server.SessionBuilder {
	return func(ctx context.Context, conn *mysql.Conn, addr string) (sql.Session, error) {
		return memory.NewSession(sql.NewBaseSession(), pro), nil
	}
}

func main() {
	pro := memory.NewDBProvider()
	engine := sqle.NewDefault(pro)

	config := server.Config{
		Protocol: "tcp",
		Address:  fmt.Sprintf("%s:%d", address, port),
	}

	s, err := server.NewServer(config, engine, sessionBuilder(pro), nil)
	if err != nil {
		fmt.Println(err)
		return
	}

	go func() {
		if err := s.Start(); err != nil {
			return
		}
	}()

	conn, err := dbsql.Open("mysql", "no_user:@tcp(localhost:3307)/")
	_, _ = conn.Exec("CREATE DATABASE demo")
	_, _ = conn.Exec("CREATE TABLE demo.user_info (id BIGINT PRIMARY KEY AUTO_INCREMENT, aid BIGINT UNSIGNED)")
	_ = conn.Close()

	mydb, err := dbsql.Open("mysql", "no_user:@tcp(localhost:3307)/demo")

	bigNum := uint64(9223372036854775808)
	// No Error now
	_, err = mydb.Exec("INSERT INTO `user_info` (id, aid) VALUES (?, ?)", 0, bigNum)
	if err != nil {
		fmt.Println(err)
	}

        // No error on execute
	rows, err := mydb.Query("SELECT * FROM user_info WHERE (aid = ?)", bigNum)
	if err != nil {
		fmt.Println(err)
	}

	for rows.Next() {
		var id int64
		var aid uint64
                // error on scan, sql: Scan error on column index 1, name "aid": converting driver.Value type int64 ("-9223372036854775808") to a uint64: invalid syntax
		if err := rows.Scan(&id, &aid); err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(id, aid)
	}
}
```
